# Generated by Django 4.0.1 on 2022-01-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='Certificate'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='resume',
            field=models.ImageField(blank=True, upload_to='Resume'),
        ),
    ]
