# Generated by Django 4.0.1 on 2022-01-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0002_psychologist_core_skills_psychologist_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='language',
            new_name='languages',
        ),
    ]
