# Generated by Django 4.0.1 on 2022-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0002_alter_psychologist_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='certificate',
            field=models.ImageField(upload_to='Certificate'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='resume',
            field=models.ImageField(upload_to='Resume'),
        ),
    ]
