# Generated by Django 4.0.1 on 2022-02-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0002_alter_consulttime_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulttime',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Date (MM/DD/YYYY):'),
        ),
    ]
