# Generated by Django 4.0.1 on 2022-01-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0003_rename_language_psychologist_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='core_skills',
            new_name='skills',
        ),
    ]
