# Generated by Django 4.0.1 on 2022-02-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0004_rename_core_skills_psychologist_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='fees',
            field=models.IntegerField(default=700),
        ),
    ]
