# Generated by Django 4.0.1 on 2022-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0004_alter_psychologist_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='date_of_birth',
            field=models.DateTimeField(blank=True),
        ),
    ]
