# Generated by Django 4.0.1 on 2022-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologist', '0006_alter_psychologist_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
