# Generated by Django 4.0.1 on 2022-02-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_paymenttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentTable',
        ),
    ]
