# Generated by Django 4.0.1 on 2022-02-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
